# backend/prometheus.yml
# Configuração do Prometheus para o ambiente de desenvolvimento.

global:
  scrape_interval: 15s # A cada quantos segundos coletar as métricas.

scrape_configs:
  - job_name: 'muzaia-backend'
    # O Prometheus vai encontrar o serviço 'backend' usando a rede do Docker.
    static_configs:
      - targets: ['backend:8000'] # O nome 'backend' é o nome do serviço no docker-compose.
