# .github/workflows/backend-ci.yml
# Workflow de Integração Contínua para o Backend

name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: '1.7.1'

      # Instala as dependências a partir do pyproject.toml do backend.
      - name: Install dependencies
        working-directory: ./backend
        run: poetry install

      # Executa os testes, garantindo que o ambiente correto seja usado.
      - name: Run tests with pytest
        working-directory: ./backend
        run: poetry run python -m pytest
